name: run_kafka_pact_tests
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
env:
  PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
jobs:
    # This workflow contains a single job called "build"
  canIDeploy:
      # The type of runner that the job will run on
    runs-on: ubuntu-latest
      # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        #       - name: Checkout
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
        # Runs a single command using the runners shell
      - name: Run kafka pact tests
        run: |
#          bash app/src/test/java/com/happymoney/domain_events_consumer/pactio/consumer/kafka/cmd/pactPublish.sh &&
          bash app/src/test/java/com/happymoney/domain_events_consumer/pactio/consumer/kafka/cmd/canIDeploy.sh
