name: tests
on:
  pull_request:
    branches:
      - master
jobs:
    # This workflow contains a single job called "build"
  build:
      # The type of runner that the job will run on
    runs-on: ubuntu-latest
      # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        #       - name: Checkout
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
        # Runs a single command using the runners shell
      - name: Run tests
        run: |
          ls
          echo running testing
